# Generated by Django 3.1.4 on 2020-12-31 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('symbol', models.CharField(help_text='英大文字 1 文字で指定してください', max_length=1, unique=True, validators=[django.core.validators.RegexValidator(message='半角英大文字 1 文字で入力してください', regex='^[A-Z]$')], verbose_name='シンボル')),
                ('food', models.CharField(choices=[('true', '必須'), ('false', '禁止'), ('select', '選択可能')], max_length=10, verbose_name='飲食物提供')),
                ('slack_ch', models.CharField(help_text='#は除いて登録してください', max_length=50, verbose_name='slack')),
                ('staff_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ')),
            ],
            options={
                'verbose_name': '企画種別',
                'verbose_name_plural': '企画種別',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
