# Generated by Django 3.0.6 on 2020-11-25 10:53

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eptid', models.CharField(max_length=200, unique=True, verbose_name='EPTID')),
                ('affiliation', models.CharField(choices=[('faculty', '教員'), ('staff', '事務'), ('student', '学生'), ('member', 'その他')], default='student', max_length=10)),
                ('stid', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='半角数字10桁で入力してください', regex='^[0-9]{10}$')], verbose_name='学生番号')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('tel', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='半角数字9桁または10桁で入力してください', regex='^[0-9]{9,10}$')], verbose_name='電話番号')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください', regex='^[ぁ-ん]+$')], verbose_name='姓（かな）')),
                ('first_name_kana', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください', regex='^[ぁ-ん]+$')], verbose_name='名（かな）')),
                ('faculty', models.CharField(choices=[('総', '総合人間学部 / 人間・環境学研究科'), ('文', '文学部 / 文学研究科'), ('教', '教育学部 / 教育学研究科'), ('法', '法学部 / 法学研究科'), ('経', '経済学部 / 経済学研究科'), ('理', '理学部 / 理学研究科'), ('医', '医学部 / 医学研究科'), ('薬', '薬学部 / 薬学研究科'), ('工', '工学部 / 工学研究科 / 情報学研究科'), ('農', '農学部 / 農学研究科'), ('他', 'その他')], max_length=1, verbose_name='学部・研究科')),
                ('grade', models.CharField(choices=[('B1', '学部1回生'), ('B2', '学部2回生'), ('B3', '学部3回生'), ('B4', '学部4回生'), ('B+', '学部5回生以上'), ('Mr', '修士課程'), ('Dr', '博士課程'), ('--', 'その他')], max_length=2, verbose_name='学年')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ')),
                ('is_admin', models.BooleanField(default=False, verbose_name='システム管理者')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
    ]
