# Generated by Django 3.0.6 on 2020-11-25 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='半角数字10桁または11桁で入力してください', regex='^[0-9]{10,11}$')], verbose_name='電話番号'),
        ),
    ]
