# Generated by Django 3.1.3 on 2020-11-29 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201125_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-start_datetime',), 'verbose_name': 'お知らせ', 'verbose_name_plural': 'お知らせ'},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='update_datetime',
        ),
        migrations.AlterField(
            model_name='notice',
            name='start_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='開始日時'),
        ),
    ]
