# Generated by Django 3.1.3 on 2020-11-29 12:25

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201129_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('slack_ch', models.CharField(help_text='#は除いて登録してください', max_length=50, verbose_name='slack')),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='構成員')),
            ],
            options={
                'verbose_name': '部局担当',
                'verbose_name_plural': '部局担当',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
