# Generated by Django 3.1.3 on 2020-11-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(choices=[('student', '学生（student）'), ('faculty', '教員（faculty）'), ('staff', '事務（staff）'), ('member', 'その他（member）')], default='student', help_text='Shibboleth の idp から取得した情報です。', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='BAN する場合はチェックを外します。', verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='システム管理者にする場合は必ずチェックしてください。', verbose_name='スタッフ'),
        ),
    ]
