# Generated by Django 3.1.3 on 2020-12-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department', verbose_name='部局担当')),
                ('to', models.ManyToManyField(related_name='message_to', to=settings.AUTH_USER_MODEL, verbose_name='宛先')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_writer', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='既読日時')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.message', verbose_name='メッセージ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メッセージ既読',
                'verbose_name_plural': 'メッセージ既読',
            },
        ),
    ]
