# Generated by Django 3.1.3 on 2020-12-02 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_message_messageread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-create_datetime',), 'verbose_name': 'メッセージ', 'verbose_name_plural': 'メッセージ'},
        ),
        migrations.CreateModel(
            name='ContactKind',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('department', models.ManyToManyField(to='home.Department', verbose_name='部局担当')),
            ],
            options={
                'verbose_name': 'お問い合わせ種別',
                'verbose_name_plural': 'お問い合わせ種別',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='本文')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='送信時刻')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contactkind', verbose_name='お問い合わせ種別')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
            },
        ),
    ]
