# Generated by Django 3.1.3 on 2020-12-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201202_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-create_datetime',), 'verbose_name': 'お問い合わせ', 'verbose_name_plural': 'お問い合わせ'},
        ),
    ]
