# Generated by Django 3.1.3 on 2020-12-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contact_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='finished',
            new_name='is_finished',
        ),
    ]
