# Generated by Django 3.1.3 on 2020-12-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_contact_messeage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messeage',
            new_name='message',
        ),
    ]
