# Generated by Django 3.1.3 on 2020-12-02 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20201202_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eptid', models.CharField(max_length=200, verbose_name='EPTID')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済')),
            ],
            options={
                'verbose_name': 'ユーザー登録トークン',
                'verbose_name_plural': 'ユーザー登録トークン',
            },
        ),
    ]
