# circleCIのバージョン指定
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      # Djangoのテストを実行
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for launch db to migrate at Django
          command: sleep 10
      - run:
          name: migrate
          command: docker-compose run django python manage.py migrate
      - run:
          name: test
          command: docker-compose run django python manage.py test
      - run:
          name: docker-compose down
          command: docker-compose down
  # サーバーにSSH接続し、デプロイを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
            - "9f:fe:67:6e:66:4d:00:f4:9d:4f:1f:a6:bc:83:7b:f5"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd penguin && git pull && docker-compose down && docker-compose up -d'

# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # masterブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: master
