# circleCIのバージョン指定
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      # Djangoのテストを実行
      - checkout
      - run:
          name: make
          command: make
      - run:
          name: start
          command: docker-compose -f docker-compose.dev.yml up --build -d
      - run:
          name: test
          command: docker-compose -f docker-compose.dev.yml run django python manage.py test
      - run:
          name: stop
          command: docker-compose -f docker-compose.dev.yml down
  # サーバーにSSH接続し、デプロイを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
            - "9f:fe:67:6e:66:4d:00:f4:9d:4f:1f:a6:bc:83:7b:f5"
      - run:
          name: ssh connetction
          command: ssh ${USER_NAME}@${HOST_NAME}
      - run:
          name: git pull
          command: cd penguin && git pull
      - run:
          name: restart docker-compose
          command: docker-compose down && docker-compose up -d

# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # masterブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: master
