# Generated by Django 3.1.4 on 2020-12-31 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSlack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_ch', models.CharField(help_text='# は除いて登録してください', max_length=50, verbose_name='Slack_ch')),
            ],
            options={
                'verbose_name': '企画登録slack',
                'verbose_name_plural': '企画登録slack',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verbose_id', models.CharField(help_text='Ex: xA-000', max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='形式が不正です！ Ex. xA-000', regex='^x[A-Z]\\-[0-9]{3}$')], verbose_name='登録コード')),
                ('food', models.BooleanField(default=False, help_text='1 ユーザーにつき、参加できる飲食物提供企画は 1 企画までです', verbose_name='飲食物を提供する')),
                ('group', models.CharField(max_length=50, verbose_name='団体名')),
                ('group_kana', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください', regex='^[ぁ-んー]+$')], verbose_name='団体名（かな）')),
                ('note', models.TextField(help_text='暫定の内容で構いません', verbose_name='企画概要・備考')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('status', models.CharField(choices=[('waiting', '待機'), ('called', '対応中'), ('pending', '保留'), ('accepted', '受理'), ('refused', '却下')], default='waiting', max_length=10, verbose_name='状態')),
                ('call_id', models.IntegerField(null=True, unique=True, verbose_name='整理番号')),
                ('finish_datetime', models.DateTimeField(blank=True, null=True, verbose_name='対応終了日時')),
                ('leader_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='企画責任者確定トークン')),
                ('finish_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_finish_staff', to=settings.AUTH_USER_MODEL, verbose_name='対応スタッフ')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.kind', verbose_name='企画種別')),
                ('temp_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_temp_leader', to=settings.AUTH_USER_MODEL, verbose_name='仮企画責任者')),
            ],
            options={
                'verbose_name': '企画登録',
                'verbose_name_plural': '企画登録',
            },
        ),
        migrations.CreateModel(
            name='VerifyToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '企画登録トークン',
                'verbose_name_plural': '企画登録トークン',
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex.「模擬1」「一般2」 案内表示画面には名前順に窓口が表示されます', max_length=10, verbose_name='名前')),
                ('kind_list', models.ManyToManyField(to='project.Kind', verbose_name='対応する企画種別')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.registration', verbose_name='企画登録')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '窓口',
                'verbose_name_plural': '窓口',
            },
        ),
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '企画登録可能ユーザー',
                'verbose_name_plural': '企画登録可能ユーザー',
            },
        ),
        migrations.CreateModel(
            name='RegisterStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '企画登録担当スタッフ',
                'verbose_name_plural': '企画登録担当スタッフ',
            },
        ),
    ]
