# Generated by Django 3.1.4 on 2020-12-29 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSlack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_ch', models.CharField(help_text='# は除いて登録してください', max_length=50, verbose_name='Slack_ch')),
            ],
            options={
                'verbose_name': '企画登録slack',
                'verbose_name_plural': '企画登録slack',
            },
        ),
        migrations.CreateModel(
            name='RegisterStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '企画登録担当スタッフ',
                'verbose_name_plural': '企画登録担当スタッフ',
            },
        ),
    ]
