# Generated by Django 3.1.4 on 2020-12-30 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='call_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='整理番号'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='verbose_id',
            field=models.CharField(help_text='Ex: xA-000', max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='形式が不正です！ Ex. xA-000', regex='^x[A-Z]\\-[0-9]{3}$')], verbose_name='登録コード'),
        ),
    ]
