# Generated by Django 3.1.4 on 2021-01-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210104_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='finish_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='処理完了日時'),
        ),
    ]
