# Generated by Django 3.1.4 on 2021-01-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210104_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterSlack',
        ),
    ]
