# Generated by Django 3.1.4 on 2020-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201231_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='name',
            field=models.CharField(help_text='Ex.「模擬1」「一般2」 案内表示画面には名前順に窓口が表示されます', max_length=10, verbose_name='名前'),
        ),
    ]
