# Generated by Django 3.1.4 on 2020-12-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('register', '0004_auto_20201231_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='kind_list',
            field=models.ManyToManyField(to='project.Kind', verbose_name='対応する企画種別'),
        ),
    ]
