# Generated by Django 3.1.4 on 2020-12-08 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('finish_datetime', models.DateTimeField(verbose_name='終了日時')),
            ],
            options={
                'verbose_name': '提出期間',
                'verbose_name_plural': '提出期間',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(help_text='50文字以内で入力してください', max_length=50, verbose_name='統一テーマ案')),
                ('description', models.CharField(help_text='400文字以内で入力してください', max_length=400, verbose_name='趣意文')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '統一テーマ案',
                'verbose_name_plural': '統一テーマ案',
            },
        ),
        migrations.CreateModel(
            name='VoteSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('finish_datetime', models.DateTimeField(verbose_name='終了日時')),
            ],
            options={
                'verbose_name': '投票期間',
                'verbose_name_plural': '投票期間',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='投票日時')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.voteschedule', verbose_name='投票期間')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.theme', verbose_name='統一テーマ案')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
            },
        ),
        migrations.CreateModel(
            name='ThemeStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '統一テーマ担当スタッフ',
                'verbose_name_plural': '統一テーマ担当スタッフ',
            },
        ),
        migrations.CreateModel(
            name='Eptid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eptid', models.CharField(max_length=200, verbose_name='eptid')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.voteschedule', verbose_name='投票期間')),
            ],
            options={
                'verbose_name': 'eptid',
                'verbose_name_plural': 'eptid',
            },
        ),
    ]
