# Generated by Django 3.1.4 on 2020-12-09 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0002_voteschedule_theme_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='強制提出操作を行った場合、担当したスタッフが記録されます', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_staff', to=settings.AUTH_USER_MODEL, verbose_name='強制提出スタッフ'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_writer', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
