# Generated by Django 3.1.4 on 2020-12-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20201209_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.CharField(help_text='100文字以内で入力してください', max_length=100, verbose_name='統一テーマ案'),
        ),
    ]
