# Generated by Django 3.1.4 on 2020-12-09 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_theme_update_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSlack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_ch', models.CharField(max_length=50, verbose_name='Slack_ch')),
            ],
            options={
                'verbose_name': '統一テーマ案slack',
                'verbose_name_plural': '統一テーマ案slack',
            },
        ),
    ]
