# Generated by Django 3.1.4 on 2020-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_themeslack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeslack',
            name='slack_ch',
            field=models.CharField(help_text='# は除いて登録してください', max_length=50, verbose_name='Slack_ch'),
        ),
    ]
