# Generated by Django 3.1.4 on 2020-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_auto_20201209_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitschedule',
            options={'verbose_name': '提出日程', 'verbose_name_plural': '提出日程'},
        ),
        migrations.AddField(
            model_name='voteschedule',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='説明文'),
        ),
    ]
