# Generated by Django 3.1.4 on 2020-12-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_auto_20201209_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteschedule',
            options={'verbose_name': '投票日程', 'verbose_name_plural': '投票日程'},
        ),
        migrations.AlterField(
            model_name='eptid',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.voteschedule', verbose_name='投票日程'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.voteschedule', verbose_name='投票日程'),
        ),
    ]
